environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: ""

branches:
  only:
    - master

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set spin false
  - npm install -g npm@6
  - npm install

# Post-install test scripts.
test_script:
  - npm run lint
  - npm test

# http://help.appveyor.com/discussions/questions/1310-delete-cache
cache:
  - node_modules -> package.json

# Don't actually build.
build: off
